app:
  host: "0.0.0.0"
  port: 8042
  workers: 2  # Number of workers for uvicorn
  receive_timeout: 120  # Timeout for receiving audio bytes in seconds
  log_dir: logs

buffer:
  prefill_time: 375  # 375ms, decrease first chunk latency
  opus_frame_duration: 20  # 20ms, opus frame duration
  
realtime_vc:
  # 设备
  device: ["cuda:0", "cuda:0"]  # 支持多卡，比如 ["cuda:0", "cuda:1"]
                                # 在多卡场景下，worker会循环依次部署到各个卡上
  
  # wav 相关
  reference_wav_path: "resources/refs/ref-24k.wav"  
  save_dir: "outputs/"  # save
  save_input: True  # is to save input wav
  save_output: True  # is to save output wav
  
  # realtime 
  SAMPLERATE: 16000   # also called common_sr
                      # 音频流在vc过程中基础采样率
                      # 不可修改，需要保证为 16k，vad，senmantic 都是 16k 模型
                      # 某些环节采样率会改变，比如dit model会更改为22050，需要再次转换回来
  BIT_DEPTH: 16  # 音频流的位深度，16位
  
  fps: 50  # 1s切分fps份，作为精度因子； 若50的话，精度就对应20ms，
           # rvc:100, seed-vc: 50
           # zc_frame = samplerate // fps, zc_frame 代表每一个精度对应的帧数
  block_time: 0.5  # 0.5 ；这里的 block time 是 0.5s                    
  crossfade_time: 0.04  # 0.04 ；用于平滑过渡的交叉渐变长度，这里设定为 0.04 秒。交叉渐变通常用于避免声音中断或“断层”现象。
  extra_time: 2.5  # 2.5；  附加时间，设置为 0.5秒。可能用于在处理音频时延长或平滑过渡的时间。
                            # 原本默认0.5，后面更新成2.5了，放在音频的前面
  extra_time_right: 0.02  # 0.02；

  # auto_f0
  is_f0: False  # 是否使用自适应音高
  total_block_for_f0: 6  # 6； 用于计算中位数音高的总块数，只有探测到人声的才会包含，6块对应 3s
  
  # vc models
  diffusion_steps: 5  # 10；                    
  inference_cfg_rate: 0.7  # 0.7
  max_prompt_length: 10.0 # 3； 
  ce_dit_difference: 2  # 2 seconds， content encoder ?
  
  # rms_mix
  rms_mix_rate: 0.9   # 0.25； 这个参数是用来控制 RMS 混合的比例，
                      # 范围是 0 到 1。
                      # 0 表示完全使用 Input 的包络，1 表示完全使用 Infer 包络。                             

  # SLOW 监测
  send_slow_threshold: 100 # 100ms, 两个客户段发送过来的音频包之间的间隔，认定SLOW的阈值
                           # 一般客户端发送过来的音频包间隔是 20ms 或者 10ms
  recv_slow_threshold: 700 # 700ms，两个客户段收到服务端发送回去的音频包之间的时间间隔，认定SLOW的阈值
                           # 服务端发送回去的包，即 block_time，默认是500ms
  vc_slow_threshold: 300  # 从累计到一个chunk开始，到完成vc并推送给客户段之间的耗时，500ms一个chunk的话，
                          # 这里认为vc时间超过300就算SLOW


models:
  is_torch_compile: False  # use torch.compile to accelerate

  # retrieval
  is_retrieval: False  # 是否启用语义特征检索模块
  index_rate: 1.0  # # 检索特征相对权重，0.0 表示不使用检索特征，1.0 表示完全使用检索特征
  index_path: "resources/retrieval/ref-tencet-female__added_IVF256_Flat_nprobe_1.index"  # faiss索引文件路径
  
  # vad
  speech_noise_thres: 0.8  # VAD  语音与噪声能量比阈值 控制噪声过滤的灵敏度。vad默认0.6

  # cfm
  t_span_schedule: "cosine"  # "linear", "cosine"， 线性 or 余弦重排，

  # 自定义模型路径，比如训练后的模型
  dit_checkpoint_path: null
  dit_config_path: null

  defalut_original_model: "tiny"  # "tiny", "small", "base"  
                                  # 如果没有指定自定义的模型路径：dit_checkpoint_path， dit_config_path。
                                  # 则使用seed-vc原始模型


